-- SmartTicket PostgreSQL schema
-- Generated from the supplied JPA entities.
-- IDs are generated by Hibernate GenerationType.UUID, so UUID columns do not
-- require database-side defaults.

BEGIN;

-- =========================================================
-- IDENTITY
-- =========================================================

CREATE TABLE users (
                       id          UUID         NOT NULL,
                       email       VARCHAR(255) NOT NULL,
                       password    VARCHAR(255) NOT NULL,
                       first_name  VARCHAR(50)  NOT NULL,
                       last_name   VARCHAR(50)  NOT NULL,
                       role        VARCHAR(30)  NOT NULL,
                       user_status VARCHAR(30)  NOT NULL,

                       CONSTRAINT pk_users PRIMARY KEY (id),
                       CONSTRAINT uk_users_email UNIQUE (email),
                       CONSTRAINT chk_users_role
                           CHECK (role IN ('ADMIN', 'CUSTOMER')),
                       CONSTRAINT chk_users_status
                           CHECK (user_status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE refresh_tokens (
                                id         UUID         NOT NULL,
                                token_hash VARCHAR(255) NOT NULL,
                                user_id    UUID         NOT NULL,
                                created_at TIMESTAMPTZ  NOT NULL,
                                expires_at TIMESTAMPTZ  NOT NULL,
                                revoked_at TIMESTAMPTZ,

                                CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
                                CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
                                CONSTRAINT fk_refresh_token_user
                                    FOREIGN KEY (user_id)
                                        REFERENCES users (id)
                                        ON DELETE CASCADE,
                                CONSTRAINT chk_refresh_tokens_expiry
                                    CHECK (expires_at > created_at),
                                CONSTRAINT chk_refresh_tokens_revoked_at
                                    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX idx_refresh_tokens_user_id
    ON refresh_tokens (user_id);

CREATE INDEX idx_refresh_tokens_expires_at
    ON refresh_tokens (expires_at);

CREATE INDEX idx_refresh_tokens_active_user_expiry
    ON refresh_tokens (user_id, expires_at)
    WHERE revoked_at IS NULL;

-- =========================================================
-- EVENT CATALOG
-- =========================================================

CREATE TABLE categories (
                            id        UUID         NOT NULL,
                            name      VARCHAR(100) NOT NULL,
                            image_url VARCHAR(500) NOT NULL,
                            active    BOOLEAN      NOT NULL DEFAULT TRUE,

                            CONSTRAINT pk_categories PRIMARY KEY (id),
                            CONSTRAINT uk_category_name UNIQUE (name)
);

CREATE TABLE competitions (
                              id       UUID         NOT NULL,
                              name     VARCHAR(150) NOT NULL,
                              country  VARCHAR(100),
                              logo_url VARCHAR(500),

                              CONSTRAINT pk_competitions PRIMARY KEY (id),
                              CONSTRAINT uk_competition_name UNIQUE (name)
);

CREATE TABLE teams (
                       id         UUID         NOT NULL,
                       name       VARCHAR(150) NOT NULL,
                       short_name VARCHAR(20),
                       country    VARCHAR(100),
                       logo_url   VARCHAR(500),

                       CONSTRAINT pk_teams PRIMARY KEY (id),
                       CONSTRAINT uk_team_name UNIQUE (name)
);

-- =========================================================
-- VENUE
-- =========================================================

CREATE TABLE venues (
                        id        UUID          NOT NULL,
                        name      VARCHAR(150)  NOT NULL,
                        address   VARCHAR(255)  NOT NULL,
                        city      VARCHAR(100)  NOT NULL,
                        country   VARCHAR(100)  NOT NULL,
                        latitude  NUMERIC(10,7),
                        longitude NUMERIC(10,7),

                        CONSTRAINT pk_venues PRIMARY KEY (id),
                        CONSTRAINT chk_venues_latitude
                            CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
                        CONSTRAINT chk_venues_longitude
                            CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE INDEX idx_venues_city_country
    ON venues (city, country);

CREATE TABLE sections (
                          id          UUID         NOT NULL,
                          name        VARCHAR(100) NOT NULL,
                          description VARCHAR(255),
                          venue_id    UUID         NOT NULL,

                          CONSTRAINT pk_sections PRIMARY KEY (id),
                          CONSTRAINT uk_section_venue_name UNIQUE (venue_id, name),
                          CONSTRAINT fk_section_venue
                              FOREIGN KEY (venue_id)
                                  REFERENCES venues (id)
                                  ON DELETE RESTRICT
);

-- The UNIQUE(venue_id, name) index already supports lookups beginning with venue_id.

CREATE TABLE seats (
                       id          UUID        NOT NULL,
                       row_label   VARCHAR(20) NOT NULL,
                       seat_number VARCHAR(20) NOT NULL,
                       section_id  UUID        NOT NULL,

                       CONSTRAINT pk_seats PRIMARY KEY (id),
                       CONSTRAINT uk_seat_section_row_number
                           UNIQUE (section_id, row_label, seat_number),
                       CONSTRAINT fk_seat_section
                           FOREIGN KEY (section_id)
                               REFERENCES sections (id)
                               ON DELETE RESTRICT
);

-- =========================================================
-- EVENT RELATIONSHIPS
-- =========================================================

CREATE TABLE competition_teams (
                                   id             UUID NOT NULL,
                                   competition_id UUID NOT NULL,
                                   team_id        UUID NOT NULL,

                                   CONSTRAINT pk_competition_teams PRIMARY KEY (id),
                                   CONSTRAINT uk_competition_team
                                       UNIQUE (competition_id, team_id),
                                   CONSTRAINT fk_competition_team_competition
                                       FOREIGN KEY (competition_id)
                                           REFERENCES competitions (id)
                                           ON DELETE CASCADE,
                                   CONSTRAINT fk_competition_team_team
                                       FOREIGN KEY (team_id)
                                           REFERENCES teams (id)
                                           ON DELETE CASCADE
);

-- UNIQUE(competition_id, team_id) covers competition_id; team_id needs its own index.
CREATE INDEX idx_competition_teams_team_id
    ON competition_teams (team_id);

CREATE TABLE events (
                        id          UUID          NOT NULL,
                        name        VARCHAR(200)  NOT NULL,
                        description VARCHAR(2000),
                        venue_id    UUID          NOT NULL,
                        category_id UUID          NOT NULL,
                        starts_at   TIMESTAMP     NOT NULL,
                        ends_at     TIMESTAMP,
                        status      VARCHAR(30)   NOT NULL,

                        CONSTRAINT pk_events PRIMARY KEY (id),
                        CONSTRAINT fk_events_venue
                            FOREIGN KEY (venue_id)
                                REFERENCES venues (id)
                                ON DELETE RESTRICT,
                        CONSTRAINT fk_events_category
                            FOREIGN KEY (category_id)
                                REFERENCES categories (id)
                                ON DELETE RESTRICT,
                        CONSTRAINT chk_events_status
                            CHECK (status IN ('DRAFT', 'SCHEDULED', 'SOLD_OUT', 'CANCELLED', 'COMPLETED')),
                        CONSTRAINT chk_events_time_range
                            CHECK (ends_at IS NULL OR ends_at > starts_at)
);

CREATE INDEX idx_events_venue_id
    ON events (venue_id);

CREATE INDEX idx_events_category_id
    ON events (category_id);

CREATE INDEX idx_events_starts_at
    ON events (starts_at);

CREATE INDEX idx_events_status_starts_at
    ON events (status, starts_at);

CREATE INDEX idx_events_category_status_starts_at
    ON events (category_id, status, starts_at);

CREATE TABLE football_matches (
                                  id             UUID NOT NULL,
                                  event_id       UUID NOT NULL,
                                  home_team_id   UUID NOT NULL,
                                  away_team_id   UUID NOT NULL,
                                  competition_id UUID NOT NULL,

                                  CONSTRAINT pk_football_matches PRIMARY KEY (id),
                                  CONSTRAINT uk_football_match_event UNIQUE (event_id),
                                  CONSTRAINT fk_football_match_event
                                      FOREIGN KEY (event_id)
                                          REFERENCES events (id)
                                          ON DELETE CASCADE,
                                  CONSTRAINT fk_football_match_home_team
                                      FOREIGN KEY (home_team_id)
                                          REFERENCES teams (id)
                                          ON DELETE RESTRICT,
                                  CONSTRAINT fk_football_match_away_team
                                      FOREIGN KEY (away_team_id)
                                          REFERENCES teams (id)
                                          ON DELETE RESTRICT,
                                  CONSTRAINT fk_football_match_competition
                                      FOREIGN KEY (competition_id)
                                          REFERENCES competitions (id)
                                          ON DELETE RESTRICT,
                                  CONSTRAINT chk_football_match_different_teams
                                      CHECK (home_team_id <> away_team_id)
);

CREATE INDEX idx_football_matches_home_team_id
    ON football_matches (home_team_id);

CREATE INDEX idx_football_matches_away_team_id
    ON football_matches (away_team_id);

CREATE INDEX idx_football_matches_competition_id
    ON football_matches (competition_id);

-- =========================================================
-- INVENTORY
-- =========================================================

CREATE TABLE event_seats (
                             id         UUID          NOT NULL,
                             event_id   UUID          NOT NULL,
                             seat_id    UUID          NOT NULL,
                             price      NUMERIC(12,2) NOT NULL,
                             status     VARCHAR(20)   NOT NULL DEFAULT 'AVAILABLE',
                             held_until TIMESTAMPTZ,

                             CONSTRAINT pk_event_seats PRIMARY KEY (id),
                             CONSTRAINT uk_event_seat_event_seat UNIQUE (event_id, seat_id),
                             CONSTRAINT fk_event_seats_event
                                 FOREIGN KEY (event_id)
                                     REFERENCES events (id)
                                     ON DELETE CASCADE,
                             CONSTRAINT fk_event_seats_seat
                                 FOREIGN KEY (seat_id)
                                     REFERENCES seats (id)
                                     ON DELETE RESTRICT,
                             CONSTRAINT chk_event_seats_price
                                 CHECK (price >= 0),
                             CONSTRAINT chk_event_seats_status
                                 CHECK (status IN ('AVAILABLE', 'HELD', 'RESERVED', 'SOLD'))
);

-- UNIQUE(event_id, seat_id) covers event_id but not seat_id alone.
CREATE INDEX idx_event_seats_seat_id
    ON event_seats (seat_id);

CREATE INDEX idx_event_seats_event_status
    ON event_seats (event_id, status);

CREATE INDEX idx_event_seats_held_until
    ON event_seats (held_until)
    WHERE status = 'HELD' AND held_until IS NOT NULL;

-- =========================================================
-- RESERVATION
-- =========================================================

CREATE TABLE reservations (
                              id           UUID          NOT NULL,
                              user_id      UUID          NOT NULL,
                              event_id     UUID          NOT NULL,
                              status       VARCHAR(30)   NOT NULL DEFAULT 'PENDING',
                              total_amount NUMERIC(12,2) NOT NULL,
                              expires_at   TIMESTAMPTZ   NOT NULL,
                              created_at   TIMESTAMPTZ   NOT NULL,

                              CONSTRAINT pk_reservations PRIMARY KEY (id),
                              CONSTRAINT fk_reservations_user
                                  FOREIGN KEY (user_id)
                                      REFERENCES users (id)
                                      ON DELETE RESTRICT,
                              CONSTRAINT fk_reservations_event
                                  FOREIGN KEY (event_id)
                                      REFERENCES events (id)
                                      ON DELETE RESTRICT,
                              CONSTRAINT chk_reservations_status
                                  CHECK (status IN ('PENDING', 'CONFIRMED', 'EXPIRED', 'CANCELLED')),
                              CONSTRAINT chk_reservations_total_amount
                                  CHECK (total_amount >= 0),
                              CONSTRAINT chk_reservations_expiry
                                  CHECK (expires_at > created_at)
);

CREATE INDEX idx_reservations_user_id
    ON reservations (user_id);

CREATE INDEX idx_reservations_event_id
    ON reservations (event_id);

CREATE INDEX idx_reservations_user_status
    ON reservations (user_id, status);

CREATE INDEX idx_reservations_event_status
    ON reservations (event_id, status);

CREATE INDEX idx_reservations_pending_expires_at
    ON reservations (expires_at)
    WHERE status = 'PENDING';

CREATE TABLE reservation_item (
                                  id             UUID          NOT NULL,
                                  reservation_id UUID          NOT NULL,
                                  event_seat_id  UUID          NOT NULL,
                                  price          NUMERIC(12,2) NOT NULL,

                                  CONSTRAINT pk_reservation_item PRIMARY KEY (id),
                                  CONSTRAINT uk_reservation_item_reservation_event_seat
                                      UNIQUE (reservation_id, event_seat_id),
                                  CONSTRAINT fk_reservation_item_reservation
                                      FOREIGN KEY (reservation_id)
                                          REFERENCES reservations (id)
                                          ON DELETE CASCADE,
                                  CONSTRAINT fk_reservation_item_event_seat
                                      FOREIGN KEY (event_seat_id)
                                          REFERENCES event_seats (id)
                                          ON DELETE RESTRICT,
                                  CONSTRAINT chk_reservation_item_price
                                      CHECK (price >= 0)
);

-- UNIQUE(reservation_id, event_seat_id) covers reservation_id.
CREATE INDEX idx_reservation_item_event_seat_id
    ON reservation_item (event_seat_id);

-- =========================================================
-- ORDER
-- =========================================================
-- NOTE: "order" is a SQL keyword. This table is quoted to match @Table(name = "order").
-- Prefer renaming the JPA table to "orders" in application code when convenient.

CREATE TABLE orders (
                         id             UUID          NOT NULL,
                         reservation_id UUID          NOT NULL,
                         order_number   VARCHAR(255)  NOT NULL,
                         status         VARCHAR(255)  NOT NULL,
                         total_amount   NUMERIC(12,2) NOT NULL,
                         created_at     TIMESTAMPTZ   NOT NULL,
                         paid_at        TIMESTAMPTZ,
                         cancelled_at   TIMESTAMPTZ,

                         CONSTRAINT pk_order PRIMARY KEY (id),
                         CONSTRAINT uk_purchase_order_order_number UNIQUE (order_number),
                         CONSTRAINT uk_order_reservation UNIQUE (reservation_id),
                         CONSTRAINT fk_order_reservation
                             FOREIGN KEY (reservation_id)
                                 REFERENCES reservations (id)
                                 ON DELETE RESTRICT,
                         CONSTRAINT chk_order_status
                             CHECK (status IN ('PENDING', 'PAYMENT_PENDING', 'PAID', 'CANCELLED', 'EXPIRED', 'PAYMENT_FAILED')),
                         CONSTRAINT chk_order_total_amount
                             CHECK (total_amount >= 0),
                         CONSTRAINT chk_order_paid_at
                             CHECK (paid_at IS NULL OR paid_at >= created_at),
                         CONSTRAINT chk_order_cancelled_at
                             CHECK (cancelled_at IS NULL OR cancelled_at >= created_at)
);

CREATE INDEX idx_order_status_created_at
    ON "orders" (status, created_at);

-- =========================================================
-- PAYMENT
-- =========================================================

CREATE TABLE payments (
                          id             UUID          NOT NULL,
                          order_id       UUID          NOT NULL,
                          transaction_id VARCHAR(255),
                          amount         NUMERIC(10,2) NOT NULL,
                          status         VARCHAR(255)  NOT NULL,
                          created_at     TIMESTAMPTZ   NOT NULL,
                          paid_at        TIMESTAMPTZ,

                          CONSTRAINT pk_payments PRIMARY KEY (id),
                          CONSTRAINT uk_payments_transaction_id UNIQUE (transaction_id),
                          CONSTRAINT fk_payments_order
                              FOREIGN KEY (order_id)
                                  REFERENCES "orders" (id)
                                  ON DELETE RESTRICT,
                          CONSTRAINT chk_payments_amount
                              CHECK (amount >= 0),
                          CONSTRAINT chk_payments_status
                              CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED')),
                          CONSTRAINT chk_payments_paid_at
                              CHECK (paid_at IS NULL OR paid_at >= created_at)
);

CREATE INDEX idx_payments_order_id
    ON payments (order_id);

CREATE INDEX idx_payments_order_status
    ON payments (order_id, status);

CREATE INDEX idx_payments_status_created_at
    ON payments (status, created_at);

COMMIT;
